#!/usr/bin/bash

# Takes one (or more) CA root certificates as ca_certs/*.pem files and generates
# an mqtt_client.inc. TLS_ROOT_CERT contains the cert(s). TLS_CLIENT_KEY and
# TLS_CLIENT_CERT are left empty.
#
# The .pem file may be generated by e.g., (on Mac OS):
#   security find-certificate \
#     -c "DigiCert Global Root G2" -a -p \
#     /System/Library/Keychains/SystemRootCertificates.keychain \
#   > digicert_global_root_g2.pem
#

if [ "${PWD##*/}" != "certs" ]; then
    echo Run this in the certs folder
    exit 1
fi
if [ -z "$MQTT_SERVER" ]; then
    echo Define MQTT_SERVER
    exit 1
fi
SERVER_NAME=$MQTT_SERVER

if [ -d "$SERVER_NAME" ]; then
    echo Run \"rm -fr $SERVER_NAME\" to regenerate
    exit 1
fi
mkdir $SERVER_NAME
echo Generating mqtt_client.inc in $PWD/$SERVER_NAME

echo -n \#define TLS_ROOT_CERT \" > $SERVER_NAME/mqtt_client.inc
cat ca_certs/*.pem | awk '{printf "%s\\n\\\n", $0}' >> $SERVER_NAME/mqtt_client.inc
echo "\"" >> $SERVER_NAME/mqtt_client.inc
echo >> $SERVER_NAME/mqtt_client.inc

echo \#define TLS_CLIENT_KEY \"\" >> $SERVER_NAME/mqtt_client.inc
echo >> $SERVER_NAME/mqtt_client.inc

echo \#define TLS_CLIENT_CERT \"\" >> $SERVER_NAME/mqtt_client.inc
echo >> $SERVER_NAME/mqtt_client.inc
